# Файл docker-compose должен начинаться с тега версии.
version: '3.3'

# Описываем сервисы
# 1 севрис - это 1 контейнер

services:
  elasticsearch:
    # image: elasticsearch:7.6.0
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.0
    # Перенаправим порты [порт компьютера]:[порт контейнера]
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      discovery.type: single-node
    networks:
      - elk

  logstash:
    #image: logstash:7.6.0
    image: docker.elastic.co/logstash/logstash:7.6.0
    ports:
      - "25000:5000"
      - "9600:9600"
      - "5046:5046"
    environment:
      XPACK_MONITORING_ENABLED: "false"
    volumes:
      # Монтируем настройки пайплайна внутрь образа
      - type: "bind"
        source: /home/makilins/Downloads/docker_elk_example/logstash/pipeline/logstash.conf
        target: /usr/share/logstash/pipeline/logstash.conf
      - type: "bind"
        source: /home/makilins/Downloads/test.log
        target: /usr/share/logstash/docs/test.log
    networks:
      - elk

  kibana:
    #image: kibana:7.6.0
    image: docker.elastic.co/kibana/kibana:7.6.0
    ports:
      - "5601:5601"
    volumes:
      # Передаем в образ настройки
      - type: "bind"
        source: /home/makilins/Downloads/docker_elk_example/kibana/config/kibana.yml
        target: /usr/share/kibana/config/kibana.yml
    networks:
      - elk

networks:
  elk:
    driver: bridge
    

  

